const DATA = {
  Vijayawada: {
    tagline: "Temple city, river views, and the practical launch point for Andhra trips.",
    description: "Vijayawada sits on the Krishna River and makes a strong home base for South and pan-India travel. It is useful for rail connections, Hyderabad flight routing, food stops, and quick heritage weekends.",
    bestTimeToVisit: "October to February",
    estimatedBudget: { mid: "₹4,000/day" },
    weather: { summer: "30-42°C", winter: "18-29°C" },
    topAttractions: ["Kanaka Durga Temple", "Prakasam Barrage", "Bhavani Island", "Undavalli Caves"],
    hiddenGems: ["Kondapalli Fort morning drive", "Riverfront food stops", "Mangalagiri temple textiles"],
    famousPlaces: [
      { name: "Kanaka Durga Temple", description: "Iconic hilltop temple overlooking the Krishna River." },
      { name: "Prakasam Barrage", description: "Evening river views and a relaxed city photo stop." },
    ],
    restaurants: [
      { name: "Babai Hotel", cuisine: "Andhra tiffins", rating: "4.4", priceRange: "₹₹" },
      { name: "Sweet Magic", cuisine: "South Indian", rating: "4.2", priceRange: "₹₹" },
    ],
    safetyTips: ["Start airport transfers early during festival traffic.", "Carry light cottons most of the year."],
  },
  Srinagar: {
    tagline: "Houseboats, gardens, old-city food, and Dal Lake evenings.",
    description: "Srinagar is the best entry point for a premium Kashmir itinerary from Vijayawada via Hyderabad. It balances lake stays, Mughal gardens, craft markets, and easy access to Gulmarg and Pahalgam.",
    bestTimeToVisit: "March to October",
    estimatedBudget: { mid: "₹12,000/day" },
    weather: { summer: "14-28°C", winter: "-2-8°C" },
    topAttractions: ["Dal Lake shikara", "Mughal Gardens", "Old Srinagar food walk", "Hazratbal Shrine"],
    hiddenGems: ["Nigeen Lake sunrise", "Papier-mache workshops", "Kahwa stops in old bazaars"],
    famousPlaces: [
      { name: "Dal Lake", description: "Shikara rides, houseboats, floating markets, and mountain-backed sunsets." },
      { name: "Mughal Gardens", description: "Layered gardens with classic Kashmir views and relaxed walking routes." },
    ],
    restaurants: [
      { name: "Ahdoos", cuisine: "Kashmiri wazwan", rating: "4.3", priceRange: "₹₹₹" },
      { name: "Chai Jaai", cuisine: "Cafe, kahwa", rating: "4.4", priceRange: "₹₹" },
    ],
    safetyTips: ["Keep ID handy for airport and hotel checks.", "Build weather buffers into onward drives."],
  },
  Gulmarg: {
    tagline: "Snow meadows, gondola views, ski lodges, and mountain slow travel.",
    description: "Gulmarg works beautifully as the luxury mountain chapter of a Kashmir trip. The best plans book gondola slots early, keep snow plans flexible, and avoid overloading the day with long transfers.",
    bestTimeToVisit: "December to March for snow, April to June for meadows",
    estimatedBudget: { mid: "₹18,000/day" },
    weather: { summer: "8-20°C", winter: "-6-5°C" },
    topAttractions: ["Gulmarg Gondola", "Snow meadow walk", "Ski lessons", "St. Mary's Church"],
    hiddenGems: ["Early meadow loop", "Kongdoori lunch window", "Quiet lodge dinners"],
    restaurants: [{ name: "The Khyber", cuisine: "Kashmiri, North Indian", rating: "4.5", priceRange: "₹₹₹₹" }],
    safetyTips: ["Book gondola tickets online.", "Do not rely on Phase 2 in poor weather."],
  },
  Pahalgam: {
    tagline: "Valleys, riverside stays, pine walks, and slower Kashmir days.",
    description: "Pahalgam is ideal for scenic private-cab circuits after Srinagar and Gulmarg. It gives the itinerary a softer final stretch with Betaab Valley, Aru Valley, and riverside cafes.",
    bestTimeToVisit: "April to October",
    estimatedBudget: { mid: "₹14,000/day" },
    weather: { summer: "10-24°C", winter: "-4-8°C" },
    topAttractions: ["Betaab Valley", "Aru Valley", "Lidder River", "Baisaran viewpoint"],
    hiddenGems: ["Riverside trout dinners", "Early Aru Valley walks", "Quiet pine trails"],
    restaurants: [{ name: "Dana Pani", cuisine: "North Indian", rating: "4.1", priceRange: "₹₹" }],
    safetyTips: ["Keep cash for local union transport.", "Start return drives early."],
  },
  Hampi: {
    tagline: "Boulder landscapes, ancient ruins, sunrise climbs, and budget-friendly backpacking.",
    description: "Hampi is one of the best low-cost heritage trips from Vijayawada by train. It shines with sunrise viewpoints, temple ruins, cycling loops, and slow cafe afternoons.",
    bestTimeToVisit: "November to February",
    estimatedBudget: { mid: "₹3,500/day" },
    weather: { summer: "25-39°C", winter: "17-30°C" },
    topAttractions: ["Virupaksha Temple", "Matanga Hill", "Lotus Mahal", "Tungabhadra coracle ride"],
    hiddenGems: ["Sanapur Lake sunset", "Early bazaar breakfast", "Cycle routes near royal enclosure"],
    restaurants: [{ name: "Mango Tree", cuisine: "Indian, cafe", rating: "4.2", priceRange: "₹₹" }],
    safetyTips: ["Avoid exposed ruins in harsh afternoon heat.", "Carry water on cycling loops."],
  },
  Gokarna: {
    tagline: "Beach hikes, hostel stays, surf mornings, and relaxed coastal sunsets.",
    description: "Gokarna pairs naturally with Hampi for a budget backpacking route. It offers low-cost hostels, beach trails, cafe work blocks, and simple bus/train connections.",
    bestTimeToVisit: "October to March",
    estimatedBudget: { mid: "₹4,000/day" },
    weather: { summer: "25-34°C", winter: "20-31°C" },
    topAttractions: ["Om Beach", "Kudle Beach", "Half Moon Beach trek", "Mahabaleshwar Temple"],
    hiddenGems: ["Morning beach trail", "Cliff cafes", "Ferry return after hike"],
    restaurants: [{ name: "Namaste Cafe", cuisine: "Cafe, coastal", rating: "4.0", priceRange: "₹₹" }],
    safetyTips: ["Check tide and light before beach hikes.", "Keep valuables minimal on beach days."],
  },
  Shillong: {
    tagline: "Cafe culture, canyon views, music nights, and the gateway to Meghalaya.",
    description: "Shillong is the most comfortable base for a friends trip through Meghalaya. It gives easy access to Laitlum, cafes, markets, and shared SUV routing.",
    bestTimeToVisit: "October to May",
    estimatedBudget: { mid: "₹6,500/day" },
    weather: { summer: "15-24°C", winter: "5-16°C" },
    topAttractions: ["Laitlum Canyon", "Ward Lake", "Police Bazaar", "Shillong cafes"],
    hiddenGems: ["Local music nights", "Early canyon drives", "Small Khasi food spots"],
    restaurants: [{ name: "Cafe Shillong", cuisine: "Cafe, continental", rating: "4.3", priceRange: "₹₹" }],
    safetyTips: ["Avoid late-night hill drives.", "Carry layers even outside winter."],
  },
  Cherrapunji: {
    tagline: "Waterfalls, root bridges, clouds, and full-day nature circuits.",
    description: "Cherrapunji is the adventure core of Meghalaya. Keep one dedicated day for the living root bridge trek and another for waterfall circuits so the trip never feels rushed.",
    bestTimeToVisit: "October to May",
    estimatedBudget: { mid: "₹7,500/day" },
    weather: { summer: "13-22°C", winter: "6-16°C" },
    topAttractions: ["Nohkalikai Falls", "Seven Sisters Falls", "Living Root Bridge", "Mawsmai Cave"],
    hiddenGems: ["Nongriat slow trek", "Foggy sunrise viewpoints", "Local Khasi meals"],
    restaurants: [{ name: "Orange Roots", cuisine: "Vegetarian Indian", rating: "4.1", priceRange: "₹₹" }],
    safetyTips: ["Use trekking shoes with grip.", "Carry ponchos and waterproof phone pouches."],
  },
  Dawki: {
    tagline: "Clear-water boating, village walks, and an easy final day.",
    description: "Dawki works best as a lighter final day after Shillong and Cherrapunji. Start boating early, keep the afternoon open, and leave enough buffer for Guwahati return.",
    bestTimeToVisit: "November to April",
    estimatedBudget: { mid: "₹5,500/day" },
    weather: { summer: "18-28°C", winter: "10-22°C" },
    topAttractions: ["Umngot River boating", "India-Bangladesh border viewpoint", "Mawlynnong village"],
    hiddenGems: ["Early boat rides", "Bamboo skywalk", "Riverside lunch stops"],
    restaurants: [{ name: "Local Khasi Homestay Meals", cuisine: "Khasi", rating: "4.2", priceRange: "₹₹" }],
    safetyTips: ["Confirm boat timings locally.", "Keep dry bags for phones and documents."],
  },
};

export function getDestinationData(cityName) {
  return DATA[String(cityName || "").trim()] || null;
}
